mods needed for MicroPython
- not creating new I2C instance within INA3221 object, passing already existing object as an arg
- not using "with" statements due to `AttributeError: 'SoftI2C' object has no attribute '__exit__'`
- `readfrom_into`, `writeto_then_readfrom` functions borrowed from (Adafruit_Blinka)[https://github.com/adafruit/Adafruit_Blinka/blob/4f4e6af0a2c2912d7662f0160849806507b125bd/src/adafruit_blinka/microcontroller/rp2040/i2c.py#L39]
- `write_then_readinto` function borrowed from (Adafruit_CircuitPython_BusDevice)[https://github.com/adafruit/Adafruit_CircuitPython_BusDevice/blob/82548ce29714f849481a356f681bb185016e983c/adafruit_bus_device/i2c_device.py#L87]